### ISSUE TITLE
When using s/goo/good in a reply thread, post the ephemeral message to the reply thread

### ISSUE THREAD

**Issue by jasonblais** [carmo-evan/mattermost-plugin-replace#10]
**Describe the bug**
When using s/goo/good in a reply thread, post the ephemeral message to the reply thread

**To Reproduce**
1. Open a reply thread
2. Post `goo day!`
3. Post `s/goo/good` to fix the typo

![image](https://user-images.githubusercontent.com/13119842/58678028-30151b00-832c-11e9-977f-857328d12aa1.png)

**Expected behavior**
Post the ephemeral message in the reply thread (which would also appear in the center channel). This would be consistent with using `/away` or `/offline` in the reply thread, for instance

![image](https://user-images.githubusercontent.com/13119842/58678042-4622db80-832c-11e9-952b-a72ba9f3e8d3.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome

**Comment by carmo-evan** [comment]
@jasonblais ready for verification in v0.2.1

**Comment by jasonblais** [comment]
@carmo-evan Confirmed, fixed! :tada:
