### ISSUE TITLE
Propose naming the plugin `Replace` instead of `replace`

### ISSUE THREAD

**Issue by jasonblais** [carmo-evan/mattermost-plugin-replace#3]
This helps with consistency with other plugins

![image](https://user-images.githubusercontent.com/13119842/57530852-2a687e80-7306-11e9-9fc1-0426a3ea6f1e.png)

(This is missing from Mattermost plugin best practice guidelines)

**Comment by carmo-evan** [comment]
I'll fix it in the next release. Thanks for the input.

**Comment by carmo-evan** [comment]
https://github.com/carmo-evan/mattermost-plugin-replace/pull/6

**Comment by carmo-evan** [comment]
@jasonblais this is ready for verification in v0.2.0.

**Comment by jasonblais** [comment]
Confirmed resolved in v0.2.0. Closing
