### ISSUE TITLE
When using the command in reply threads, replace text for the most recent reply in thread

### ISSUE THREAD

**Issue by jasonblais** [carmo-evan/mattermost-plugin-replace#4]
Repro:

1. Post a message `hey test`
2. Post a message `This is a test`
3. For the message you posted in step 1, open its reply thread by clicking the "reply arrow" associated with that post

![image](https://user-images.githubusercontent.com/13119842/57531104-b8446980-7306-11e9-822a-170752a22893.png)

4. Type `/s test/testing` in the reply thread on the right-hand side

Observed: Message posted in step 2 is updated.
Expected: Message posted in step 1 is updated, given it's in the reply thread.

![image](https://user-images.githubusercontent.com/13119842/57531032-8c28e880-7306-11e9-9fdb-bcb3e0092963.png)

**Comment by johnthompson365** [comment]
Thanks for the contribution Evan. It would be great if you are able to look into the issue Jason has raised as I think that will make it a plugin we can recommend more broadly as it supports the threaded conversations. If I can help in anyway let me know.

**Comment by carmo-evan** [comment]
Hi! For some reason I did not get emails for this. I'll look into it.

**Comment by carmo-evan** [comment]
@jasonblais this is ready for verification in v0.2.0.

**Comment by jasonblais** [comment]
This is resolved, however, I would propose posting the resulting ephemeral message in the reply thread as well

![image](https://user-images.githubusercontent.com/13119842/58678028-30151b00-832c-11e9-977f-857328d12aa1.png)

This would be consistent with using `/away` or `/offline` in the reply thread, for instance

![image](https://user-images.githubusercontent.com/13119842/58678042-4622db80-832c-11e9-952b-a72ba9f3e8d3.png)

I can open a separate issue for it, if you'd prefer.

**Comment by carmo-evan** [comment]
Yes, please.

**Comment by jasonblais** [comment]
Here you go: https://github.com/carmo-evan/mattermost-plugin-replace/issues/10
